apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZG9kbzRkcHJj
  CLOUDINARY_KEY: MzQ3MjIyNjY2ODk0Njcz
  CLOUDINARY_SECRET: a3RSandiSFQyYlBfU09EZGVSckVjaUlQS3VZ 
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lZbWhoY21kaGRqSTNNVElpTENKaElqb2lZMjF0Y200M2NYSTFNV0ZvZURKeGMyUjJhM1kyWnpOc2JTSjkub0dqVjdnc1BWNFpMV0otS0l1a1E1UQ==
  DB_URL: bW9uZ29kYitzcnY6Ly9NeXVzZXI6QmhhcmdhdkAyN0BjbHVzdGVyMC5keThyaTFrLm1vbmdvZGIubmV0Lz9hcHBOYW1lPUNsdXN0ZXIw
